version: '3.5'


services:
  namenode:
    image: anostdev/hadoop-master:1.0.0-hadoop2.7.7
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=scac-cluster-2019
    env_file:
      - ./hadoop.env
    ports:
      - 50070:50070
      - 8020:8020
    networks: 
      - scac-network
    


  datanode:
    image: anostdev/hadoop-worker:1.0.0-hadoop2.7.7
    depends_on: 
      - namenode
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    ports:
      - 50075:50075
    networks: 
      - scac-network
    depends_on: 
      - namenode


  # resourcemanager:
  #     image: uhopper/hadoop-resourcemanager
  #     hostname: resourcemanager
  #     container_name: resourcemanager
  #     domainname: hadoop
  #     networks:
  #       - scac-network
  #     environment:
  #       - GANGLIA_HOST=<GMOND-RECEIVER-HOST>
  #       - CORE_CONF_fs_defaultFS=hdfs://hadoop:8020
  #       - YARN_CONF_yarn_log___aggregation___enable=true


  # nodemanager1:
  #   image: uhopper/hadoop-nodemanager
  #   hostname: nodemanager1
  #   container_name: nodemanager1
  #   domainname: hadoop
  #   networks:
  #     - scac-network
  #   env_file:
  #     - ./hadoop.env
  #   environment:
  #     - GANGLIA_HOST=<GMOND-RECEIVER-HOST>
  #     - CORE_CONF_fs_defaultFS=hdfs://hadoop:8020
  #     #- YARN_CONF_yarn_resourcemanager_hostname=<localhost>
  #     - YARN_CONF_yarn_log___aggregation___enable=true
  #     - YARN_CONF_yarn_nodemanager_remote___app___log___dir=/app-logs



volumes:
  datanode:
  namenode:


networks:
  scac-network:
    external: true
    name: scac-network-2019