version: "3.5"

services:


  zookeeper:
    image: confluentinc/cp-zookeeper:latest #zookeeper:3.3
    container_name: zookeeper
    ports:
      - 2181:2181

    environment: 
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - scac-network-2019


  kafka:
    image: confluentinc/cp-kafka:latest #wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    networks:
      - scac-network-2019
    env_file:
      - ./kafka.env
    depends_on:
      - zookeeper
  
networks:
  scac-network-2019:
    external: true
    name: scac-network-2019

    
