version: '3' 
services:
  namenode:
    image: anostdev/hadoop-master:1.0.0-hadoop2.7.7
    container_name: namenode
    volumes:
      - ../volumes/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks: 
      - hadoop
    ports:
      - 50070:50070
      - 8020:8020
    


  datanode:
    image: anostdev/hadoop-worker:1.0.0-hadoop2.7.7
    depends_on: 
      - namenode
    volumes:
      - ../volumes/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    networks: 
      - hadoop
    ports:
      - 50075:50075
    depends_on: 
      - namenode
    
    
  
  spark-master:
    image: anostdev/spark-master:1.0.1-hadoop2.7
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop.env
    environment: 
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    networks: 
      - hadoop


  spark-worker-1:
    image: anostdev/spark-worker:1.0.1-hadoop2.7
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks: 
      - hadoop
    ports:
      - 8081:8081
    env_file:
      - ./hadoop.env


  spark-worker-2:
    image: anostdev/spark-worker:1.0.1-hadoop2.7
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks: 
      - hadoop
    ports:
      - 8082:8081
    env_file:
      - ./hadoop.env

  spark-worker-3:
    image: anostdev/spark-worker:1.0.1-hadoop2.7
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks: 
      - hadoop
    ports:
      - 8083:8081
    env_file:
      - ./hadoop.env

  spark-notebook:
    image: bde2020/spark-notebook:2.1.0-hadoop2.8-hive
    container_name: spark-notebook
    env_file:
      - ./hadoop.env
    ports:
      - 9001:9001
    networks: 
      - hadoop

  hue:
    image: bde2020/hdfs-filebrowser:3.11
    ports:
      - 8090:8088
    environment:
      - NAMENODE_HOST=namenode
    networks: 
      - hadoop

networks: 
  hadoop: